name: Build and push to GCR Main branch

on:
  push:
    branches: [ main ]

jobs:

    deploy:
    
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:

          IMAGE_NAME: gcr.io/cloud-run-327804/cloud-run-project/v${{ github.run_number }}
        steps:

        - name: Check Out Repo 
          uses: actions/checkout@v2
        
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCR_PROJECT_ID }}
            service_account_email: ${{ secrets.GCR_SERVICE_NAME }}
            service_account_key: ${{ secrets.GCR_KEY }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install req
          run: pip install -r requirements.txt
          
        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Create New Instance Template
          run: gcloud compute instance-templates create-with-container instance-template-${{ github.run_number }} --tags=http-server --container-env=DATABASE_URL=${{ secrets.PROD_DB_URL }} --container-image=gcr.io/cloud-run-327804/cloud-run-project/v${{ github.run_number }}:latest
        
        - name: Edit Instance Group with new Instance Template
          run: gcloud compute instance-groups managed set-instance-template instance-group-2 --zone=europe-west4-a --template=instance-template-$${{ github.run_number }}
